name: Build

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  # Cancel any in-progress workflows for this workflow/branch combination
  group: ${{ github.workflow }}-${{ github.ref }} # Create a group identifier for the workflow/branch
  cancel-in-progress: true

jobs:
    build:
        name: Build and test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Xcode version
              uses: maxim-lobanov/setup-xcode@v1.6.0
              with:
                xcode-version: '16.1.0'
            - name: Show current version of Xcode
              run: xcodebuild -version
            - name: Run tests
              run: ./run_tests.sh